steps:
  - name: maven:3-jdk-8
    id: package
    entrypoint: mvn
    args: ['package','-Dmaven.test.skip=true']

  - name: maven:3-jdk-8
    id: deploy
    entrypoint: mvn
    args: ['deploy', '-Dmaven.test.skip=true']
    waitFor:
      - package
